/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Calculadora;

import java.awt.Color;
import java.awt.Toolkit;

/**
 *
 * @author Maby
 */
public class NewClass extends javax.swing.JFrame {

    /**
     * Creates new form codigo
     */
    public NewClass() {
        
        
        
        initComponents();
        
        // cambiar icono de jFrame
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/icon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    double n1,n2;
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        resumenOperacion = new javax.swing.JLabel();
        operacion = new javax.swing.JLabel();
        tipoOperacion = new javax.swing.JLabel();
        signo = new javax.swing.JLabel();
        btn_7 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btn_8 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        btn_9 = new javax.swing.JButton();
        btn_suma = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        btn_5 = new javax.swing.JButton();
        btn_6 = new javax.swing.JButton();
        btn_resta = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_1 = new javax.swing.JButton();
        btn_multiplicacion = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_division = new javax.swing.JButton();
        btn_0 = new javax.swing.JButton();
        btn_punto = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        borraU = new javax.swing.JButton();
        btn_porcentaje = new javax.swing.JButton();
        raizCuadrada = new javax.swing.JButton();
        btn_exp = new javax.swing.JButton();
        btn_calcular = new javax.swing.JButton();
        memoria = new javax.swing.JButton();
        memoria1 = new javax.swing.JButton();
        borrarMemoria = new javax.swing.JButton();
        historial = new javax.swing.JLabel();
        historial2 = new javax.swing.JLabel();
        memoriaNum = new javax.swing.JLabel();
        onOff = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GretchenSoft inc Calculadora 1.0v");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(25, 34, 43));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resumenOperacion.setForeground(new java.awt.Color(189, 146, 64));
        resumenOperacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        resumenOperacion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(resumenOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 17, 147, 54));

        operacion.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        operacion.setForeground(new java.awt.Color(189, 146, 64));
        operacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        operacion.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), new java.awt.Color(204, 204, 204)));
        operacion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(operacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 97, 382, 84));

        tipoOperacion.setForeground(new java.awt.Color(189, 146, 64));
        tipoOperacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tipoOperacion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(tipoOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 193, 160, 50));

        signo.setForeground(new java.awt.Color(189, 146, 64));
        signo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        signo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(signo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 170, 50));

        btn_7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_7.setText("7");
        btn_7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_7ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 50, 50));

        jButton3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton3.setText("C");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 1073, 50, 50));

        btn_8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_8.setText("8");
        btn_8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_8ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 50, 50));

        jButton5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton5.setText("C");
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 781, 50, 50));

        jButton7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton7.setText("C");
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 781, 50, 50));

        btn_9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_9.setText("9");
        btn_9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_9ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 50, 50));

        btn_suma.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_suma.setText("+");
        btn_suma.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sumaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_suma, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 50, 50));

        btn_4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_4.setText("4");
        btn_4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 50, 50));

        btn_5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_5.setText("5");
        btn_5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 50, 50));

        btn_6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_6.setText("6");
        btn_6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_6ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 50, 50));

        btn_resta.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_resta.setText("-");
        btn_resta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_restaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_resta, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 50, 50));

        btn_3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_3.setText("3");
        btn_3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 50, 50));

        btn_1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_1.setText("1");
        btn_1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 50, 50));

        btn_multiplicacion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_multiplicacion.setText("*");
        btn_multiplicacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_multiplicacionActionPerformed(evt);
            }
        });
        jPanel1.add(btn_multiplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 50, 50));

        btn_2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_2.setText("2");
        btn_2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 50, 50));

        btn_division.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_division.setText("/");
        btn_division.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_divisionActionPerformed(evt);
            }
        });
        jPanel1.add(btn_division, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 50, 50));

        btn_0.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_0.setText("0");
        btn_0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_0ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, 50, 50));

        btn_punto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_punto.setText(".");
        btn_punto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_puntoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_punto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 50, 50));

        borrar.setText("C");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });
        jPanel1.add(borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 110, 50));

        borraU.setText("CE");
        borraU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borraUActionPerformed(evt);
            }
        });
        jPanel1.add(borraU, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 110, 50));

        btn_porcentaje.setText("%");
        btn_porcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_porcentajeActionPerformed(evt);
            }
        });
        jPanel1.add(btn_porcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 110, 50));

        raizCuadrada.setText("RAIZ");
        raizCuadrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raizCuadradaActionPerformed(evt);
            }
        });
        jPanel1.add(raizCuadrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 160, 60));

        btn_exp.setText("EXP");
        btn_exp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_expActionPerformed(evt);
            }
        });
        jPanel1.add(btn_exp, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 490, 110, 50));

        btn_calcular.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btn_calcular.setText("=");
        btn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularActionPerformed(evt);
            }
        });
        jPanel1.add(btn_calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 160, 190));

        memoria.setText("m");
        memoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memoriaActionPerformed(evt);
            }
        });
        jPanel1.add(memoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 140, 60));

        memoria1.setText("mr");
        memoria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memoria1ActionPerformed(evt);
            }
        });
        jPanel1.add(memoria1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 140, 60));

        borrarMemoria.setText("mc");
        borrarMemoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarMemoriaActionPerformed(evt);
            }
        });
        jPanel1.add(borrarMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, 140, 60));

        historial.setForeground(new java.awt.Color(189, 146, 64));
        historial.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        historial.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(historial, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 160, 50));

        historial2.setForeground(new java.awt.Color(189, 146, 64));
        historial2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        historial2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(historial2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, 160, 50));

        memoriaNum.setForeground(new java.awt.Color(189, 146, 64));
        memoriaNum.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        memoriaNum.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(memoriaNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 160, 50));

        onOff.setText("Modo Oscuro");
        onOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onOffActionPerformed(evt);
            }
        });
        jPanel1.add(onOff, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 510, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed
        addNum("7");  // TODO add your handling code here:
    }//GEN-LAST:event_btn_7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8ActionPerformed
         addNum("8"); // TODO add your handling code here:
    }//GEN-LAST:event_btn_8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9ActionPerformed
        addNum("9");  // TODO add your handling code here:
    }//GEN-LAST:event_btn_9ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
         addNum("4"); // TODO add your handling code here:
    }//GEN-LAST:event_btn_4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
        addNum("5");  // TODO add your handling code here:
    }//GEN-LAST:event_btn_5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
        addNum("6");  // TODO add your handling code here:
    }//GEN-LAST:event_btn_6ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
       addNum("1");   // TODO add your handling code here:
    }//GEN-LAST:event_btn_1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
        addNum("2");  // TODO add your handling code here:
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
       addNum("3"); // TODO add your handling code here:
    }//GEN-LAST:event_btn_3ActionPerformed

    private void btnpuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_puntoActionPerformed
       agregarPunto();
    }//GEN-LAST:event_btn_puntoActionPerformed

    private void borraUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borraUActionPerformed
        deleteChar();
    }//GEN-LAST:event_borraUActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
       operacion.setText("");
        resumenOperacion.setText("");
        tipoOperacion.setText("");
        signo.setText("");

    }//GEN-LAST:event_borrarActionPerformed

    private void btnsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sumaActionPerformed
       n1 = Double.parseDouble(operacion.getText());
        tipoOperacion.setText("SUMA");
        signo.setText("+");
        resumenOperacion.setText(operacion.getText() + signo.getText());
        operacion.setText("");
    }//GEN-LAST:event_btn_sumaActionPerformed

    private void btnrestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_restaActionPerformed
        n1 = Double.parseDouble(operacion.getText());
        tipoOperacion.setText("RESTA");
        signo.setText("-");
        resumenOperacion.setText(operacion.getText() + signo.getText());
        operacion.setText("");
    }//GEN-LAST:event_btn_restaActionPerformed

    private void btnmultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_multiplicacionActionPerformed
         n1 = Double.parseDouble(operacion.getText());
        tipoOperacion.setText("multiplicado");
        signo.setText("*");
        resumenOperacion.setText(operacion.getText() + signo.getText());
        operacion.setText("");
    }//GEN-LAST:event_btn_multiplicacionActionPerformed

    private void btndivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_divisionActionPerformed
         n1 = Double.parseDouble(operacion.getText());
        tipoOperacion.setText("dividido");
        signo.setText("/");
        resumenOperacion.setText(operacion.getText() + signo.getText());
        operacion.setText("");
    }//GEN-LAST:event_btn_divisionActionPerformed

    private void btnporcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_porcentajeActionPerformed
          n1 = Double.parseDouble(operacion.getText());
        tipoOperacion.setText("porcentaje");
        signo.setText("%");
        resumenOperacion.setText(operacion.getText() + signo.getText());
        operacion.setText("");
    }//GEN-LAST:event_btn_porcentajeActionPerformed

    private void raizCuadradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raizCuadradaActionPerformed
          double raiz = Double.parseDouble(operacion.getText());

        double res = Math.sqrt(raiz);
        String salida = String.valueOf(res);
        operacion.setText(salida);

        //Historial
        String memoria2 = historial.getText();
        if (memoria2.isEmpty()) {

            historial.setText(raiz + " √ " + " =" + Double.toString(res));
        } else {
            String memoria = historial.getText();
            historial.setText("");
            historial.setText(raiz + " √ " + " =" + Double.toString(res));
            historial2.setText(memoria);
        }
    }//GEN-LAST:event_raizCuadradaActionPerformed

    private void btnexpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_expActionPerformed
        n1 = Double.parseDouble(operacion.getText());
        tipoOperacion.setText("Exp");
        signo.setText("^");
        resumenOperacion.setText(operacion.getText() + signo.getText());
        operacion.setText("");
    }//GEN-LAST:event_btn_expActionPerformed

    private void btncalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularActionPerformed
       
        try {

            n2 = Double.parseDouble(operacion.getText());
            // FUNCION SUMA
            if ("+".equals(signo.getText())) {
                resumenOperacion.setText(resumenOperacion.getText() + operacion.getText());
                double suma = n1 + n2;

                operacion.setText(Double.toString(suma));
                tipoOperacion.setText("");
                signo.setText("");

                //Historial
                String memoria2 = historial.getText();
                if (memoria2.isEmpty()) {

                    historial.setText(resumenOperacion.getText() + " = " + Double.toString(suma));
                } else {
                    String memoria = historial.getText();
                    historial.setText("");
                    historial.setText(resumenOperacion.getText() + " = " + Double.toString(suma));
                    historial2.setText(memoria);
                }

                //FUNCION RESTA
            } else if ("-".equals(signo.getText())) {

                resumenOperacion.setText(resumenOperacion.getText() + operacion.getText());
                double resta = n1 - n2;

                operacion.setText(Double.toString(resta));
                tipoOperacion.setText("");
                signo.setText("");

                //Historial
                String memoria2 = historial.getText();
                if (memoria2.isEmpty()) {

                    historial.setText(resumenOperacion.getText() + " = " + Double.toString(resta));
                } else {
                    String memoria = historial.getText();
                    historial.setText("");
                    historial.setText(resumenOperacion.getText() + " = " + Double.toString(resta));
                    historial2.setText(memoria);
                }

                //FUNCION MULTIPLICACION
            } else if ("*".equals(signo.getText())) {
                resumenOperacion.setText(resumenOperacion.getText() + operacion.getText());
                double multiplicacion = n1 * n2;
                operacion.setText(Double.toString(multiplicacion));
                tipoOperacion.setText("");
                signo.setText("");

                //Historial
                String memoria2 = historial.getText();
                if (memoria2.isEmpty()) {

                    historial.setText(resumenOperacion.getText() + " = " + Double.toString(multiplicacion));
                } else {
                    String memoria = historial.getText();
                    historial.setText("");
                    historial.setText(resumenOperacion.getText() + " = " + Double.toString(multiplicacion));
                    historial2.setText(memoria);
                }

                //FUNCION DIVISION
            } else if ("/".equals(signo.getText())) {
                resumenOperacion.setText(resumenOperacion.getText() + operacion.getText());
                double division = n1 / n2;
                operacion.setText(Double.toString(division));
                tipoOperacion.setText("");
                signo.setText("");

                //Historial
                String memoria2 = historial.getText();
                if (memoria2.isEmpty()) {

                    historial.setText(resumenOperacion.getText() + " = " + Double.toString(division));
                } else {
                    String memoria = historial.getText();
                    historial.setText("");
                    historial.setText(resumenOperacion.getText() + " = " + Double.toString(division));
                    historial2.setText(memoria);
                }

                //FUNCION PORCENTAJE
            } else if ("%".equals(signo.getText())) {
                resumenOperacion.setText(resumenOperacion.getText() + operacion.getText());
                double porcentaje = n1 * (n2 / 100);
                operacion.setText(Double.toString(porcentaje));
                tipoOperacion.setText("");
                signo.setText("");

                //Historial
                String memoria2 = historial.getText();
                if (memoria2.isEmpty()) {

                    historial.setText(resumenOperacion.getText() + " = " + Double.toString(porcentaje));
                } else {
                    String memoria = historial.getText();
                    historial.setText("");
                    historial.setText(resumenOperacion.getText() + " = " + Double.toString(porcentaje));
                    historial2.setText(memoria);
                }

                // FUNCION DE POTENCIA
            } else if ("^".equals(signo.getText())) {

                resumenOperacion.setText(resumenOperacion.getText() + operacion.getText());
                double elevado = Math.pow(n1, n2);
                operacion.setText(Double.toString(elevado));
                tipoOperacion.setText("");
                signo.setText("");
                //Historial
                String memoria2 = historial.getText();
                if (memoria2.isEmpty()) {

                    historial.setText(resumenOperacion.getText() + " = " + Double.toString(elevado));
                } else {
                    String memoria = historial.getText();
                    historial.setText("");
                    historial.setText(resumenOperacion.getText() + " = " + Double.toString(elevado));
                    historial2.setText(memoria);
                }

            }
        } catch (Exception e) {

            borrar.doClick();
            operacion.setText("error");

        }
//    TERMINA EL IGUAL
    }//GEN-LAST:event_btn_calcularActionPerformed

    private void memoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memoriaActionPerformed
       memoriaNum.setText(operacion.getText());
    }//GEN-LAST:event_memoriaActionPerformed

    private void memoria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memoria1ActionPerformed
       operacion.setText(memoriaNum.getText());
    }//GEN-LAST:event_memoria1ActionPerformed

    private void borrarMemoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarMemoriaActionPerformed
        memoriaNum.setText("");
    }//GEN-LAST:event_borrarMemoriaActionPerformed

    private void onOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onOffActionPerformed
        if (onOff.isSelected()) {
        
          jPanel1.setBackground(Color.WHITE);
          onOff.setText("modo claro" );
        
        
        }else{
        
        jPanel1.setBackground(Color.decode("#19222B"));
          onOff.setText("modo oscuro" );
        
        }
    }//GEN-LAST:event_onOffActionPerformed

    private void btn_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_0ActionPerformed
       addNum("0");
    }//GEN-LAST:event_btn_0ActionPerformed
    //*************************FUNCIONES PROPIAS **************************************************//
    public void addNum(String numero) {

        operacion.setText(operacion.getText() + numero);

    }

    public void deleteChar() {
        try {
            String valorActual = operacion.getText();
            String nuevoValor = valorActual.substring(0, valorActual.length() - 1);
            operacion.setText(nuevoValor);
        } catch (Exception e) {
            borrar.doClick();
            operacion.setText("error");

        }
    }

    //FUNCION DE PUNTO
    public void agregarPunto() {
        String valorActual = operacion.getText();

        // Verificamos si la cadena está vacía
        if (valorActual.isEmpty()) {
            // Si está vacía, agregamos un cero antes del punto
            valorActual = "0.";
        } else {
            // Verificamos si ya hay un punto
            boolean tienePunto = valorActual.contains(".");
            if (!tienePunto) {
                valorActual += ".";
            }
        }

        operacion.setText(valorActual);
    }
            
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borraU;
    private javax.swing.JButton borrar;
    private javax.swing.JButton borrarMemoria;
    private javax.swing.JButton btn_0;
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_5;
    private javax.swing.JButton btn_6;
    private javax.swing.JButton btn_7;
    private javax.swing.JButton btn_8;
    private javax.swing.JButton btn_9;
    private javax.swing.JButton btn_calcular;
    private javax.swing.JButton btn_division;
    private javax.swing.JButton btn_exp;
    private javax.swing.JButton btn_multiplicacion;
    private javax.swing.JButton btn_porcentaje;
    private javax.swing.JButton btn_punto;
    private javax.swing.JButton btn_resta;
    private javax.swing.JButton btn_suma;
    private javax.swing.JLabel historial;
    private javax.swing.JLabel historial2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton memoria;
    private javax.swing.JButton memoria1;
    private javax.swing.JLabel memoriaNum;
    private javax.swing.JToggleButton onOff;
    private javax.swing.JLabel operacion;
    private javax.swing.JButton raizCuadrada;
    private javax.swing.JLabel resumenOperacion;
    private javax.swing.JLabel signo;
    private javax.swing.JLabel tipoOperacion;
    // End of variables declaration//GEN-END:variables
}
