/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Maby
 */
import java.awt.*;
import javax.swing.*;
import javax.swing.border.EmptyBorder;

public class JFramePrincipal extends JFrame {

    private JPanel contentPane;

    // Constructor de la clase JFramePrincipal
    public JFramePrincipal() {
        // Configuración de cierre de la ventana
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        // Establecemos el tamaño y posición del JFrame
        setBounds(100, 100, 450, 300);

        // Creamos el panel principal y lo configuramos
        contentPane = new JPanel();
        contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
        setContentPane(contentPane); // Asignamos el panel a la ventana
    }

    // Método principal para ejecutar la aplicación
    public static void main(String[] args) {
        // Ejecutamos la aplicación en el hilo de eventos de Swing
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    // Creamos y mostramos el JFrame
                    JFramePrincipal frame = new JFramePrincipal();
                    frame.setVisible(true);  // Hacemos visible el frame
                } catch (Exception e) {
                    e.printStackTrace();  // Manejamos cualquier excepción
                }
            }
        });
    }
}
    /**
     * Creates new form NewCalc
     */
    public NewCalc() {
        initComponents();
    }
        private double num1 = 0;
        private double num2 = 0;
        private String operator;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        display = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jB1 = new javax.swing.JButton();
        jB2 = new javax.swing.JButton();
        jB3 = new javax.swing.JButton();
        jB4 = new javax.swing.JButton();
        jB5 = new javax.swing.JButton();
        jB6 = new javax.swing.JButton();
        jB7 = new javax.swing.JButton();
        jB8 = new javax.swing.JButton();
        jB9 = new javax.swing.JButton();
        jBcero = new javax.swing.JButton();
        jBsum = new javax.swing.JButton();
        JBresta = new javax.swing.JButton();
        jBmultiplic = new javax.swing.JButton();
        jBdiv = new javax.swing.JButton();
        jBequal = new javax.swing.JButton();

        javax.swing.GroupLayout displayLayout = new javax.swing.GroupLayout(display);
        display.setLayout(displayLayout);
        displayLayout.setHorizontalGroup(
            displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        displayLayout.setVerticalGroup(
            displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );

        jB1.setText("1");
        jB1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB1MouseClicked(evt);
            }
        });

        jB2.setText("2");
        jB2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB2MouseClicked(evt);
            }
        });

        jB3.setText("3");
        jB3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB3MouseClicked(evt);
            }
        });

        jB4.setText("4");
        jB4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB4MouseClicked(evt);
            }
        });

        jB5.setText("5");
        jB5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB5MouseClicked(evt);
            }
        });

        jB6.setText("6");
        jB6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB6MouseClicked(evt);
            }
        });

        jB7.setText("7");
        jB7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB7MouseClicked(evt);
            }
        });

        jB8.setText("8");
        jB8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB8MouseClicked(evt);
            }
        });

        jB9.setText("9");
        jB9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB9MouseClicked(evt);
            }
        });

        jBcero.setText("0");
        jBcero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBceroMouseClicked(evt);
            }
        });

        jBsum.setText("+");
        jBsum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBsumMouseClicked(evt);
            }
        });

        JBresta.setText("-");
        JBresta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBrestaMouseClicked(evt);
            }
        });

        jBmultiplic.setText("*");
        jBmultiplic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBmultiplicMouseClicked(evt);
            }
        });

        jBdiv.setText("/");
        jBdiv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBdivMouseClicked(evt);
            }
        });

        jBequal.setText("=");
        jBequal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBequalMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jB7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jB9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jB1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jB2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jB3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jB4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jB5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jB6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jBcero, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBequal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBsum, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBresta, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBdiv, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBmultiplic, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jBsum, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(JBresta, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBmultiplic, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBdiv, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jB1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jB4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jB7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBcero, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBequal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(display, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(729, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jB1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB1MouseClicked
        if (display.getText().isEmpty()) {
            display.setText("1");
            num1 = 1; 
        } else {
            String valorAnt = display.getText();
            display.setText(valorAnt + "1");
            num2 = 1;
        }
    }                                   

    }//GEN-LAST:event_jB1MouseClicked

    private void jB2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB2MouseClicked
        if (display.getText().isEmpty()) {
            display.setText("2");
            num1 = 2; 
        } else {
            String valorAnt = display.getText();
            display.setText(valorAnt + "2");
            num2 = 2;
        }
    }                                   

    }//GEN-LAST:event_jB2MouseClicked

    private void jB3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB3MouseClicked
        if (display.getText().isEmpty()) {
            display.setText("3");
            num1 = 3; 
        } else {
            String valorAnt = display.getText();
            display.setText(valorAnt + "3");
            num2 = 3;
        }
    }                                   

    }//GEN-LAST:event_jB3MouseClicked

    private void jBsumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBsumMouseClicked
        num1 = Double.parseDouble(display.getText());
    // Establecemos el operador como "+"
    operator = "+";
    // Limpiamos el display para el siguiente número
    display.setText("+");
    }                                    

    }//GEN-LAST:event_jBsumMouseClicked

    private void JBrestaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBrestaMouseClicked
        num1 = Double.parseDouble(display.getText());
    // Establecemos el operador como "+"
    operator = "-";
    // Limpiamos el display para el siguiente número
    display.setText("-");
    }                                    

    }//GEN-LAST:event_JBrestaMouseClicked

    private void jB6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB6MouseClicked
        if (display.getText().isEmpty()) {
            display.setText("6");
            num1 = 6; 
        } else {
            String valorAnt = display.getText();
            display.setText(valorAnt + "6");
            num2 = 6;
        }
    }                                   

    }//GEN-LAST:event_jB6MouseClicked

    private void jB5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB5MouseClicked
        if (display.getText().isEmpty()) {
            display.setText("5");
            num1 = 5; 
        } else {
            String valorAnt = display.getText();
            display.setText(valorAnt + "5");
            num2 = 5;
        }
    }                                   

    }//GEN-LAST:event_jB5MouseClicked

    private void jB4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB4MouseClicked
        if (display.getText().isEmpty()) {
            display.setText("4");
            num1 = 4; 
        } else {
            String valorAnt = display.getText();
            display.setText(valorAnt + "4");
            num2 = 4;
        }
    }                                   

    }//GEN-LAST:event_jB4MouseClicked

    private void jBmultiplicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBmultiplicMouseClicked
        num1 = Double.parseDouble(display.getText());
    // Establecemos el operador como "+"
    operator = "*";
    // Limpiamos el display para el siguiente número
    display.setText("*");
    }                                    

    }//GEN-LAST:event_jBmultiplicMouseClicked

    private void jBdivMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBdivMouseClicked
        num1 = Double.parseDouble(display.getText());
    // Establecemos el operador como "+"
    operator = "/";
    // Limpiamos el display para el siguiente número
    display.setText("/");

    }//GEN-LAST:event_jBdivMouseClicked

    private void jB7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB7MouseClicked
        if (display.getText().isEmpty()) {
            display.setText("7");
            num1 = 7; 
        } else {
            String valorAnt = display.getText();
            display.setText(valorAnt + "7");
            num2 = 7;
        }
    }//GEN-LAST:event_jB7MouseClicked

    private void jB8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB8MouseClicked
        if (display.getText().isEmpty()) {
            display.setText("8");
            num1 = 8; 
        } else {
            String valorAnt = display.getText();
            display.setText(valorAnt + "8");
            num2 = 8;
        }
    }//GEN-LAST:event_jB8MouseClicked

    private void jB9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB9MouseClicked
        if (display.getText().isEmpty()) {
            display.setText("9");
            num1 = 9; 
        } else {
            String valorAnt = display.getText();
            display.setText(valorAnt + "9");
            num2 = 9;
        }
    }//GEN-LAST:event_jB9MouseClicked

    private void jBceroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBceroMouseClicked
        if (display.getText().isEmpty()) {
            display.setText("0");
            num1 = 0; 
        } else {
            String valorAnt = display.getText();
            display.setText(valorAnt + "0");
            num2 = 0;
        }
    }//GEN-LAST:event_jBceroMouseClicked

    private void jBequalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBequalMouseClicked
        num2 = Double.parseDouble(display.getText());

         // Realizamos la operación dependiendo del operador
         double result = 0; // Inicializamos la variable result
         switch (operator) {
             case "+":
                 result = num1 + num2;
                 break;
             case "-":
                 result = num1 - num2;
                 break;
             case "*":
                 result = num1 * num2;
                 break;
             case "/":
                 if (num2 != 0) { // Comprobamos que no se divida por cero
                     result = num1 / num2;
                 } else {
                     display.setText("Error"); // Mensaje de error en caso de división por cero
                     return; // Salimos del método
                 }
                 break;
             default:
                 display.setText("Error"); // Mensaje de error si el operador no es válido
                 return; // Salimos del método
         }

    // Mostramos el resultado en el display
    display1.setText(String.valueOf(result));
}

    }//GEN-LAST:event_jBequalMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBresta;
    private javax.swing.JPanel display;
    private javax.swing.JButton jB1;
    private javax.swing.JButton jB2;
    private javax.swing.JButton jB3;
    private javax.swing.JButton jB4;
    private javax.swing.JButton jB5;
    private javax.swing.JButton jB6;
    private javax.swing.JButton jB7;
    private javax.swing.JButton jB8;
    private javax.swing.JButton jB9;
    private javax.swing.JButton jBcero;
    private javax.swing.JButton jBdiv;
    private javax.swing.JButton jBequal;
    private javax.swing.JButton jBmultiplic;
    private javax.swing.JButton jBsum;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
